---
- name: nginx install
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: copy
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: '0644'

- name: check config
  shell: nginx -t

- name: reload
  service:
    name: nginx
    state: restarted